export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';


// AUTHENTICATION

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SIGNUP = "USER__SIGNUP";
export const USER_SIGNOUT = "USER_SIGNOUT";

// COMMON

export const GET_LOGO_REQUEST = "GET_LOGO_REQUEST";
export const GET_LOGO_SUCCESS = "GET_LOGO_SUCCESS";

// DASHBOARD

export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS";
export const DASHBOARD_IS_LOADING = "DASHBOARD_IS_LOADING";
export const DASHBOARD_IS_NOT_LOADING = "DASHBOARD_IS_NOT_LOADING";


// VOCAB

export const GET_VOCAB_SUCCESS = "GET_VOCAB_SUCCESS";

export const GET_VOCAB_AND_GRAMMAR_SUCCESS = "GET_VOCAB_AND_GRAMMAR_SUCCESS";

//SIDEBAR
export const TOGGLE_SIDEBAR_BUTTON = "TOGGLE_SIDEBAR_BUTTON";
export const ENABLE_SIDEBAR_BUTTON = "ENABLE_SIDEBAR_BUTTON";

export const UPDATE_HIGHLIGHT_WORD = "UPDATE_HIGHLIGHT_WORD";

export const TOGGLE_SIDEBAR = " TOGGLE_SIDEBAR";

export const GET_SAVED_WORDS = "GET_SAVED_WORDS";

export const GET_LIST_OF_SAVED_WORDS = "GET_LIST_OF_SAVED_WORDS";

export const UPDATE_SAVED_WORDS = "UPDATE_SAVED_WORDS";

export const ADD_SAVED_WORD = "ADD_SAVED_WORD";
export const DELETE_SAVED_WORD = "DELETE_SAVED_WORD";

export const INIT_STORY = "INIT_STORY";

export const LEAVE_STORY = "LEAVE_STORY";

export const RESET_STATUS = "RESET_STATUS";

export const UPDATE_DRAWER_SIZE = "UPDATE_DRAWER_SIZE";
export const RESET_SIDEBAR = "RESET_SIDEBAR";
export const ADD_TO_SAVED_WORD = "ADD_TO_SAVED_WORD";
export const REMOVE_FROM_SAVED_WORD = "REMOVE_FROM_SAVED_WORD";

//INSTRUCTOR

export const CHANGE_INSTRUCTOR_SELECTED_MENU = "CHANGE_INSTRUCTOR_SELECTED_MENU";
export const INSTRUCTOR_INIT = "INSTRUCTOR_INIT";
export const ADD_NEW_STORY = "ADD_NEW_STORY";
export const GET_STORY_LIST = "GET_STORY_LIST";
export const ADD_STORY_INFO = "ADD_STORY_INFO";
export const CLOSE_STATUS_BAR = "CLOSE_STATUS_BAR";

//STORIES
export const RESET_STORIES = "RESET_STORIES";
export const STORY_IS_LOADING = "STORY_IS_LOADING";
export const STORY_IS_NOT_LOADING = "STORY_IS_NOT_LOADING";
export const SAVE_HYPOTHESIS = "SAVE_HYPOTHESIS"