export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';


// AUTHENTICATION

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SIGNUP = "USER__SIGNUP";
export const USER_SIGNOUT = "USER_SIGNOUT";

// COMMON

export const GET_LOGO_REQUEST = "GET_LOGO_REQUEST";
export const GET_LOGO_SUCCESS = "GET_LOGO_SUCCESS";

// DASHBOARD

export const GET_DASHBOARD_INIT = "GET_LOGO_INIT";
export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS";
export const GET_DASHBOARD_ASSET = "GET_DASHBOARD_ASSET";

// VOCAB

export const GET_VOCAB_REQUEST = "GET_VOCAB_REQUEST";
export const GET_VOCAB_SUCCESS = "GET_VOCAB_SUCCESS";